import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-packaging-material-index-price-audit",
  "engine": "recovery",
  "title": "Packaging Material Index-Price Audit",
  "shortTitle": "Packaging Material Index-Price Audit",
  "tagline": "Recalculate indexed packaging prices and recover formula, lag, conversion, freight, and volume errors.",
  "industry": "Packaging Procurement Recovery",
  "buyer": "Consumer goods manufacturers and packaging buyers",
  "uiPort": 4704,
  "apiPort": 5704,
  "accent": "#7e22ce",
  "currency": "USD",
  "primaryOutcome": "Packaging Material Index-Price Audit converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect supplier agreements, packaging specifications, resin paper and metal indexes, formula lags, conversion costs, freight, volumes, invoices, credits, and rebates in one accountable workflow. Recalculate indexed packaging prices and recover formula, lag, conversion, freight, and volume errors.",
  "calculation": {
    "actualKey": "chargedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "Charged or Paid Amount",
    "expectedLabel": "Evidence-Supported Amount",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "Packaging Material Index-Price Audit evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("packaging-agreement-library","PMI01","Packaging agreement library","Execute packaging agreement library using supplier agreements, packaging specifications, resin paper and metal indexes, formula lags, conversion costs, freight, volumes, invoices, credits, and rebates.","Produce a governed packaging agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Packaging SKU","text","Supplier / Packaging SKU · Standard Case"],["caseReference","Packaging agreement library Reference","text","PMI01-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1346250],["supportedAmount","Evidence-Supported Amount","currency",1130850],["domainDriver","Material Family","select","Corrugated",["Corrugated","Plastic resin","Aluminum"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Packaging agreement library case","SKU specification registry case","Commodity index ingestion case","Index publication validation case","Formula lag calculation case"]}),
feature("sku-specification-registry","PMI02","SKU specification registry","Execute sku specification registry using supplier agreements, packaging specifications, resin paper and metal indexes, formula lags, conversion costs, freight, volumes, invoices, credits, and rebates.","Produce a governed sku specification registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Packaging SKU","text","Supplier / Packaging SKU · Standard Case"],["caseReference","SKU specification registry Reference","text","PMI02-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1346250],["supportedAmount","Evidence-Supported Amount","currency",1130850],["domainDriver","Material Family","select","Corrugated",["Corrugated","Plastic resin","Aluminum"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Packaging agreement library case","SKU specification registry case","Commodity index ingestion case","Index publication validation case","Formula lag calculation case"]}),
feature("commodity-index-ingestion","PMI03","Commodity index ingestion","Execute commodity index ingestion using supplier agreements, packaging specifications, resin paper and metal indexes, formula lags, conversion costs, freight, volumes, invoices, credits, and rebates.","Produce a governed commodity index ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Packaging SKU","text","Supplier / Packaging SKU · Standard Case"],["caseReference","Commodity index ingestion Reference","text","PMI03-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1346250],["supportedAmount","Evidence-Supported Amount","currency",1130850],["domainDriver","Material Family","select","Corrugated",["Corrugated","Plastic resin","Aluminum"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Packaging agreement library case","SKU specification registry case","Commodity index ingestion case","Index publication validation case","Formula lag calculation case"]}),
feature("index-publication-validation","PMI04","Index publication validation","Execute index publication validation using supplier agreements, packaging specifications, resin paper and metal indexes, formula lags, conversion costs, freight, volumes, invoices, credits, and rebates.","Produce a governed index publication validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Packaging SKU","text","Supplier / Packaging SKU · Standard Case"],["caseReference","Index publication validation Reference","text","PMI04-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1346250],["supportedAmount","Evidence-Supported Amount","currency",1130850],["domainDriver","Material Family","select","Corrugated",["Corrugated","Plastic resin","Aluminum"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Packaging agreement library case","SKU specification registry case","Commodity index ingestion case","Index publication validation case","Formula lag calculation case"]}),
feature("formula-lag-calculation","PMI05","Formula lag calculation","Execute formula lag calculation using supplier agreements, packaging specifications, resin paper and metal indexes, formula lags, conversion costs, freight, volumes, invoices, credits, and rebates.","Produce a governed formula lag calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Packaging SKU","text","Supplier / Packaging SKU · Standard Case"],["caseReference","Formula lag calculation Reference","text","PMI05-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1346250],["supportedAmount","Evidence-Supported Amount","currency",1130850],["domainDriver","Material Family","select","Corrugated",["Corrugated","Plastic resin","Aluminum"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Packaging agreement library case","SKU specification registry case","Commodity index ingestion case","Index publication validation case","Formula lag calculation case"]}),
feature("conversion-cost-validation","PMI06","Conversion cost validation","Execute conversion cost validation using supplier agreements, packaging specifications, resin paper and metal indexes, formula lags, conversion costs, freight, volumes, invoices, credits, and rebates.","Produce a governed conversion cost validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Packaging SKU","text","Supplier / Packaging SKU · Standard Case"],["caseReference","Conversion cost validation Reference","text","PMI06-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1346250],["supportedAmount","Evidence-Supported Amount","currency",1130850],["domainDriver","Material Family","select","Corrugated",["Corrugated","Plastic resin","Aluminum"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Packaging agreement library case","SKU specification registry case","Commodity index ingestion case","Index publication validation case","Formula lag calculation case"]}),
feature("freight-component-audit","PMI07","Freight component audit","Execute freight component audit using supplier agreements, packaging specifications, resin paper and metal indexes, formula lags, conversion costs, freight, volumes, invoices, credits, and rebates.","Produce a governed freight component audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Packaging SKU","text","Supplier / Packaging SKU · Standard Case"],["caseReference","Freight component audit Reference","text","PMI07-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1346250],["supportedAmount","Evidence-Supported Amount","currency",1130850],["domainDriver","Material Family","select","Corrugated",["Corrugated","Plastic resin","Aluminum"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Packaging agreement library case","SKU specification registry case","Commodity index ingestion case","Index publication validation case","Formula lag calculation case"]}),
feature("volume-tier-calculation","PMI08","Volume tier calculation","Execute volume tier calculation using supplier agreements, packaging specifications, resin paper and metal indexes, formula lags, conversion costs, freight, volumes, invoices, credits, and rebates.","Produce a governed volume tier calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Packaging SKU","text","Supplier / Packaging SKU · Standard Case"],["caseReference","Volume tier calculation Reference","text","PMI08-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1346250],["supportedAmount","Evidence-Supported Amount","currency",1130850],["domainDriver","Material Family","select","Corrugated",["Corrugated","Plastic resin","Aluminum"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Packaging agreement library case","SKU specification registry case","Commodity index ingestion case","Index publication validation case","Formula lag calculation case"]}),
feature("lightweighting-adjustment","PMI09","Lightweighting adjustment","Execute lightweighting adjustment using supplier agreements, packaging specifications, resin paper and metal indexes, formula lags, conversion costs, freight, volumes, invoices, credits, and rebates.","Produce a governed lightweighting adjustment decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Packaging SKU","text","Supplier / Packaging SKU · Standard Case"],["caseReference","Lightweighting adjustment Reference","text","PMI09-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1346250],["supportedAmount","Evidence-Supported Amount","currency",1130850],["domainDriver","Material Family","select","Corrugated",["Corrugated","Plastic resin","Aluminum"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Packaging agreement library case","SKU specification registry case","Commodity index ingestion case","Index publication validation case","Formula lag calculation case"]}),
feature("scrap-factor-control","PMI10","Scrap factor control","Execute scrap factor control using supplier agreements, packaging specifications, resin paper and metal indexes, formula lags, conversion costs, freight, volumes, invoices, credits, and rebates.","Produce a governed scrap factor control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Packaging SKU","text","Supplier / Packaging SKU · Standard Case"],["caseReference","Scrap factor control Reference","text","PMI10-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1346250],["supportedAmount","Evidence-Supported Amount","currency",1130850],["domainDriver","Material Family","select","Corrugated",["Corrugated","Plastic resin","Aluminum"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Packaging agreement library case","SKU specification registry case","Commodity index ingestion case","Index publication validation case","Formula lag calculation case"]}),
feature("price-effective-date-check","PMI11","Price effective-date check","Execute price effective-date check using supplier agreements, packaging specifications, resin paper and metal indexes, formula lags, conversion costs, freight, volumes, invoices, credits, and rebates.","Produce a governed price effective-date check decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Packaging SKU","text","Supplier / Packaging SKU · Standard Case"],["caseReference","Price effective-date check Reference","text","PMI11-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1346250],["supportedAmount","Evidence-Supported Amount","currency",1130850],["domainDriver","Material Family","select","Corrugated",["Corrugated","Plastic resin","Aluminum"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Packaging agreement library case","SKU specification registry case","Commodity index ingestion case","Index publication validation case","Formula lag calculation case"]}),
feature("invoice-recalculation","PMI12","Invoice recalculation","Execute invoice recalculation using supplier agreements, packaging specifications, resin paper and metal indexes, formula lags, conversion costs, freight, volumes, invoices, credits, and rebates.","Produce a governed invoice recalculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Packaging SKU","text","Supplier / Packaging SKU · Standard Case"],["caseReference","Invoice recalculation Reference","text","PMI12-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1346250],["supportedAmount","Evidence-Supported Amount","currency",1130850],["domainDriver","Material Family","select","Corrugated",["Corrugated","Plastic resin","Aluminum"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Packaging agreement library case","SKU specification registry case","Commodity index ingestion case","Index publication validation case","Formula lag calculation case"]}),
feature("supplier-dispute-workflow","PMI13","Supplier dispute workflow","Execute supplier dispute workflow using supplier agreements, packaging specifications, resin paper and metal indexes, formula lags, conversion costs, freight, volumes, invoices, credits, and rebates.","Produce a governed supplier dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Packaging SKU","text","Supplier / Packaging SKU · Standard Case"],["caseReference","Supplier dispute workflow Reference","text","PMI13-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1346250],["supportedAmount","Evidence-Supported Amount","currency",1130850],["domainDriver","Material Family","select","Corrugated",["Corrugated","Plastic resin","Aluminum"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Packaging agreement library case","SKU specification registry case","Commodity index ingestion case","Index publication validation case","Formula lag calculation case"]}),
feature("credit-reconciliation","PMI14","Credit reconciliation","Execute credit reconciliation using supplier agreements, packaging specifications, resin paper and metal indexes, formula lags, conversion costs, freight, volumes, invoices, credits, and rebates.","Produce a governed credit reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Packaging SKU","text","Supplier / Packaging SKU · Standard Case"],["caseReference","Credit reconciliation Reference","text","PMI14-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1346250],["supportedAmount","Evidence-Supported Amount","currency",1130850],["domainDriver","Material Family","select","Corrugated",["Corrugated","Plastic resin","Aluminum"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Packaging agreement library case","SKU specification registry case","Commodity index ingestion case","Index publication validation case","Formula lag calculation case"]}),
feature("material-supplier-analytics","PMI15","Material supplier analytics","Execute material supplier analytics using supplier agreements, packaging specifications, resin paper and metal indexes, formula lags, conversion costs, freight, volumes, invoices, credits, and rebates.","Produce a governed material supplier analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Packaging SKU","text","Supplier / Packaging SKU · Standard Case"],["caseReference","Material supplier analytics Reference","text","PMI15-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1346250],["supportedAmount","Evidence-Supported Amount","currency",1130850],["domainDriver","Material Family","select","Corrugated",["Corrugated","Plastic resin","Aluminum"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Packaging agreement library case","SKU specification registry case","Commodity index ingestion case","Index publication validation case","Formula lag calculation case"]})
]);
